### ISSUE TITLE
Float / Decimal support

### ISSUE THREAD

**Issue by stubbulon5** [kimwalisch/calculator#6]
Hi there, does this library support float or decimal's in the expression string eg "1.5 + 2.5" ? 

Cheers

**Comment by kimwalisch** [comment]
Sorry, but this is currently not supported.

It should not be too difficult to modify calculator.hpp to support double and float but you need to do it yourself. I could help though explaining what needs to be modified if you are interested.

**Comment by stubbulon5** [comment]
Thank you. I may have a crack at it. It certainly is an elegant piece of code (and very concise when compared to the other libraries)

Cheers.

**Comment by skYdr1ve** [comment]
Hi, I'm writing double module and i want to ask. Could you help explaining what needs to be modified?

**Comment by ClearSeve** [comment]
no~ Can't believe not supported
